### ISSUE TITLE
Python on Linux: can't install python modules in 2024-08-01 snapshot

### ISSUE THREAD

**Issue by FinbarArgus** [opencor/opencor#2800]
When trying to install modules in the new snapshot (OpenCOR-2024-08-01-Linux), I get the following error:

farg967:~/software/OpenCOR-2024-08-01-Linux/python/bin$ ./python3.12 -m pip install pandas
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 68, in <module>
    from _sha2 import sha512 as _sha512
ModuleNotFoundError: No module named '_sha2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 245, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 68, in <module>
    from _sha2 import sha512 as _sha512
ModuleNotFoundError: No module named '_sha2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 245, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 68, in <module>
    from _sha2 import sha512 as _sha512
ModuleNotFoundError: No module named '_sha2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 245, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 68, in <module>
    from _sha2 import sha512 as _sha512
ModuleNotFoundError: No module named '_sha2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 245, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 68, in <module>
    from _sha2 import sha512 as _sha512
ModuleNotFoundError: No module named '_sha2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 245, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 68, in <module>
    from _sha2 import sha512 as _sha512
ModuleNotFoundError: No module named '_sha2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 245, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
ERROR:root:code for hash sha3_224 was not found.
Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 68, in <module>
    from _sha2 import sha512 as _sha512
ModuleNotFoundError: No module named '_sha2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 245, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_224
ERROR:root:code for hash sha3_256 was not found.
Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 68, in <module>
    from _sha2 import sha512 as _sha512
ModuleNotFoundError: No module named '_sha2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 245, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_256
ERROR:root:code for hash sha3_384 was not found.
Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 68, in <module>
    from _sha2 import sha512 as _sha512
ModuleNotFoundError: No module named '_sha2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 245, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_384
ERROR:root:code for hash sha3_512 was not found.
Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 68, in <module>
    from _sha2 import sha512 as _sha512
ModuleNotFoundError: No module named '_sha2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 245, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_512
ERROR:root:code for hash shake_128 was not found.
Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 68, in <module>
    from _sha2 import sha512 as _sha512
ModuleNotFoundError: No module named '_sha2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 245, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type shake_128
ERROR:root:code for hash shake_256 was not found.
Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 68, in <module>
    from _sha2 import sha512 as _sha512
ModuleNotFoundError: No module named '_sha2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 245, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type shake_256
Traceback (most recent call last):
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 68, in <module>
    from _sha2 import sha512 as _sha512
ModuleNotFoundError: No module named '_sha2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/site-packages/pip/__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/site-packages/pip/_internal/build_env.py", line 14, in <module>
    from pip._vendor.certifi import where
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
    from .core import contents, where
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
    from importlib.resources import as_file, files
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/importlib/resources/__init__.py", line 3, in <module>
    from ._common import (
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/importlib/resources/_common.py", line 3, in <module>
    import tempfile
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/random.py", line 71, in <module>
    from hashlib import sha512 as _sha512
ImportError: cannot import name 'sha512' from 'hashlib' (/home/farg967/software/OpenCOR-2024-08-01-Linux/python/lib/python3.12/hashlib.py)

**Comment by agarny** [comment]
Argh, if anything I can indeed confirm that I am getting the same result (while everything is fine on macOS). :/

**Comment by agarny** [comment]
@FinbarArgus, I am a bit puzzled. I tried it the previous snapshot (i.e. `2024-04-10`) and I got the same problem. Was it also the case for you?

Just to confirm, I also tried the `2024-04-10` and `2024-08-01` snapshots on both Windows and macOS and it all works fine. So, it looks like it's a pure Linux issue. @dbrnz, any idea of what might be wrong? I would imagine that the issue is with our copy of Python and/or its packages on Linux?

**Comment by FinbarArgus** [comment]
@agarny I can't access the previous snapshots (https://opencor.ws/downloads/previousSnapshots.html says no snapshots available) but it was working fine with version 0.7.1

**Comment by agarny** [comment]
> @agarny I can't access the previous snapshots (https://opencor.ws/downloads/previousSnapshots.html says no snapshots available) but it was working fine with version 0.7.1

Yes, I forgot to add the `2024-04-10` snapshot to the `Previous snapshots` page when I added the `2024-08-01`. I realised that earlier. So, I have just updated the `Previous snapshots` page and it should all be fine now. Just do a forrce refresh (`Ctrl`+`Shift`+`R`).

As for things working for `0.7.1`, yes, it was a different version of Python. We have updated the version of Python in `2024-04-10` (to help one of you guys' students). So, the problem is likely to be there since none of my recent changes had anything to do with Python _per se_.

**Comment by FinbarArgus** [comment]
Ahh, that will be Stephen, I'll ask him how he got around it.

**Comment by agarny** [comment]
> Ahh, that will be Stephen, I'll ask him how he got around it.

Thanks, that could indeed help us to fix the issue with Linux.

**Comment by agarny** [comment]
@dbrnz, any chance you could have a quick look into it? Cheers.

**Comment by dbrnz** [comment]
Sure, I'll have a look tomorrow.

**Comment by agarny** [comment]
> Sure, I'll have a look tomorrow.

Great, thanks a lot!

**Comment by dbrnz** [comment]
Hmm, things just worked for me...
```
$ wget https://opencor.ws/downloads/snapshots/2024-08-01/OpenCOR-2024-08-01-Linux.tar.gz
$ cd OpenCOR-2024-08-01-Linux
$ tar xzf OpenCOR-2024-08-01-Linux.tar.gz
$ python/bin/python3.12 -m pip install pandas
Collecting pandas
  Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in ./python/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./python/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in ./python/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 32.4 MB/s eta 0:00:00
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 28.7 MB/s eta 0:00:00
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 26.2 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.2 pytz-2024.1 tzdata-2024.1
```

**Comment by dbrnz** [comment]
This is running under Ubuntu 20.04.

**Comment by dbrnz** [comment]
Aha, under Ubuntu 22 I get exactly the same errors as @FinbarArgus. @agarny it looks as if we need to have a separate Ubuntu 22 version...

**Comment by agarny** [comment]
I just checked my Ubuntu Docker container and it's also Ubuntu 22.04 LTS, hence it wasn't working for me either.

Regarding Ubuntu support, I feel like we should just support Ubuntu 22.04 LTS and above. After all, OpenCOR 0.7.x comes with Python 3.7.5 while OpenCOR 0.8 will be coming with Python 3.12.2 (although our codebase mentions a `BUILD_TAG` value of `opencor-3.12.3`?!). So, to update our minimum Ubuntu requirements is reasonable, not least since Ubuntu 22.04 LTS is more than 2 years old already.

**Comment by dbrnz** [comment]
And do we also need to consider Ubuntu 24.04 LTS ?

**Comment by agarny** [comment]
If OpenCOR is to work on Ubuntu 22.04 LTS then we want it to work on any (existing) version which comes after it. So, yes, by supporting Ubuntu 22.04 LTS, I also mean Ubuntu 24.04 LTS.

Otherwise, are you saying that we need different binaries for different versions of Ubuntu? If so, why were we able to get Python 3.7.5 to work fine for different versions of Ubuntu before?

**Comment by dbrnz** [comment]
Well I guess I should try setting up a Ubuntu 24.04 LTS system.

I'm currently running a Ubuntu 22 build -- I don't expect any issues as the original Python upgrade work was under 22.04 until you pointed out the need to support Ubuntu 20.

**Comment by dbrnz** [comment]
Hmm, maybe not quite so straight forward as under 22.04 I'm getting errors like the following, which aren't too different from the ones above, so I'm wondering if there's something else going on.
```
[158/792] cd /home/dave/build/opencor/src/plugins/third...ckages/matplotlib --verbose src/matplotlib_3.8.2.2.diff
FAILED: src/plugins/thirdParty/PythonPackages/CMakeFiles/patchMatplotlib /home/dave/build/opencor/build/src/plugins/thirdParty/PythonPackages/CMakeFiles/patchMatplotlib
cd /home/dave/build/opencor/src/plugins/thirdParty/PythonPackages && /home/dave/build/opencor/build/lib/../python/bin/python3 -s scripts/patch.py --strip=2 --directory=/home/dave/build/opencor/ext/PythonPackages/lib/python3.12/site-packages/matplotlib --verbose src/matplotlib_3.8.2.2.diff
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/home/dave/build/opencor/src/plugins/thirdParty/PythonPackages/scripts/patch.py", line 28, in <module>
    import urllib2 as urllib_request
ModuleNotFoundError: No module named 'urllib2'
```
and
```
  File "/home/dave/build/opencor/build/python/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
ERROR:root:code for hash sha3_224 was not found.
```

**Comment by dbrnz** [comment]
Hmm again. Under Ubuntu 22.04 the following works, so the original issue is to do with libraries not being found.
```
$ wget https://opencor.ws/downloads/snapshots/2024-08-01/OpenCOR-2024-08-01-Linux.tar.gz
$ tar xzf OpenCOR-2024-08-01-Linux.tar.gz
$ cd OpenCOR-2024-08-01-Linux
$ export LD_LIBRARY_PATH=/home/dave/OpenCOR-2024-08-01-Linux/lib
$ python/bin/python3.12 -m pip install pandas
Collecting pandas
  Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in ./python/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./python/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in ./python/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 36.7 MB/s eta 0:00:00
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 33.6 MB/s eta 0:00:00
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 30.4 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.2 pytz-2024.1 tzdata-2024.1
```

**Comment by agarny** [comment]
> Well I guess I should try setting up a Ubuntu 24.04 LTS system.

FWIW, I have an [Ubuntu Docker](https://github.com/agarny/ubuntu-docker) that can be used to build, run, test, and package libCellML, libOpenCOR, and OpenCOR on the x86-64 version of Ubuntu 22.04 LTS. With a bit of luck, it can be made to work with Ubuntu 24.04 LTS by just updating the first line of the `Dockerfile` file.

**Comment by agarny** [comment]
> Hmm again. Under Ubuntu 22.04 the following works, so the original issue is to do with libraries not being found.
> 
> ```
> $ export LD_LIBRARY_PATH=/home/dave/OpenCOR-2024-08-01-Linux/lib
> ```

Didn't we account for this at some point? 🤔

**Comment by agarny** [comment]
> > Well I guess I should try setting up a Ubuntu 24.04 LTS system.
> 
> FWIW, I have an [Ubuntu Docker](https://github.com/agarny/ubuntu-docker) that can be used to build, run, test, and package libCellML, libOpenCOR, and OpenCOR on the x86-64 version of Ubuntu 22.04 LTS. With a bit of luck, it can be made to work with Ubuntu 24.04 LTS by just updating the first line of the `Dockerfile` file.

Well, it doesn't work out of te box. Ubuntu 24.04 LTS must have changed the name and/or version of some libraries.

**Comment by FinbarArgus** [comment]
> > Hmm again. Under Ubuntu 22.04 the following works, so the original issue is to do with libraries not being found.
> > ```
> > $ export LD_LIBRARY_PATH=/home/dave/OpenCOR-2024-08-01-Linux/lib
> > ```
> 
> Didn't we account for this at some point? 🤔

Ah shit, yes I had to do this to install some libraries when using OpenCOR-0-7-1-Linux as well. I thought I tested it here but I must have misspelt something. Hopefully this works for installing all of the other libraries in OpenCOR-2024-08-01-Linux. I will check today.

**Comment by dbrnz** [comment]
Here's the difference.

Ubuntu 22.04 without `LD_LIBRARY_PATH` set:
```
$ ldd python/lib/python3.12/lib-dynload/_hashlib.so
	linux-vdso.so.1 (0x00007fff0aff6000)
	libcrypto.so.1.1 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8e1889c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8e18ae5000)
```

Ubuntu 22.04 with `LD_LIBRARY_PATH` set:
```
$ ldd python/lib/python3.12/lib-dynload/_hashlib.so
	linux-vdso.so.1 (0x00007ffff6d35000)
	libcrypto.so.1.1 => /home/dave/OpenCOR-2024-08-01-Linux/lib/libcrypto.so.1.1 (0x00007f3657810000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f36575da000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f36575d5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f36575d0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3657b11000)
```

Ubuntu 20.04 without `LD_LIBRARY_PATH` set:
```
$ ldd python/lib/python3.12/lib-dynload/_hashlib.so
	linux-vdso.so.1 (0x00007ffd393d1000)
	libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f7bf1811000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7bf161f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7bf1619000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7bf15f6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7bf1b0b000)
```

Under 20.04 we are using the system libraries, not the ones we bundled; 22.04 has `/lib/x86_64-linux-gnu/libcrypto.so.3` and not version 1.1, hence the errors.

We are running `python/bin/python3.12` from the command line so is the fix to set our library path into our Python? Or to set `LD_LIBRARY_PATH` when running from the command line?

I'm wondering if GUI OpenCOR manages to find the correct libraries. For some reason I can no longer RDP to my headless Ubuntu system so can't easily check -- @FinbarArgus or @agarny do you have an OpenCOR Python window available under Ubuntu 22 in which to try `import hashlib`?

**Comment by agarny** [comment]
Hmm... indeed regarding `./pythonshell` setting `LD_LIBRARY_PATH`! I thought we had managed to find a solution that didn't rely on `LD_LIBRARY_PATH` but clearly not!

Anyway, keeping everything in mind, your suggestion seems sensible to me. The only thing is that rather than `./runpython`, I would just use `./python`, including on macOS, while `.\python.bat` on Windows. In other words, I am going to add the following scripts:
- **Windows:**
```batch
@ECHO OFF

TITLE Running Python...

CALL "%~dp0Python\bin\python.exe" %*
```
- **Linux:**
```shell
#!/bin/sh

appDir="$(cd "$(dirname "$0")"; pwd)"

export LD_LIBRARY_PATH="${appDir}/lib":$LD_LIBRARY_PATH

"${appDir}/python/bin/python" "$@"
```
- **macOS:**
```shell
#!/bin/sh

"$(cd "$(dirname "$0")"; pwd)/@CMAKE_PROJECT_NAME@.app/Contents/Frameworks/Python/bin/python" "$@"
```

**Comment by dbrnz** [comment]
The little difficulty is that under Linux `./python` is a directory... :)

**Comment by agarny** [comment]
Yes, that's why I am working on having the Python folder called `Python` (like on Windows and macOS), but I must have missed something since things are not working at the moment. :/

**Comment by agarny** [comment]
Ok, just to confirm that everything works fine. IOW, I can now do:
```shell
$ ./python -m pip install pandas
Collecting pandas
  Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in ./Python/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./Python/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in ./Python/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 25.8 MB/s eta 0:00:00
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 30.8 MB/s eta 0:00:00
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 29.0 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.2 pytz-2024.1 tzdata-2024.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: /root/OpenCOR/build/Python/bin/python -m pip install --upgrade pip
```

**Comment by agarny** [comment]
In fact, I am going to add a `pip` script too since people will often want to install Python packages.

**Comment by agarny** [comment]
Ok, all good! Onto issue #2801 and then I will be releasing a new snapshot, @FinbarArgus.

**Comment by FinbarArgus** [comment]
python3.12 doesn't seem to be in Python/bin anymore

farg967:~/software/OpenCOR-2024-08-23-Linux/Python/bin$ ls
runipython  runjupyter

So I get the following errors:

farg967:~/software/OpenCOR-2024-08-23-Linux$ ./pip install pandas
./pip: 7: /home/farg967/software/OpenCOR-2024-08-23-Linux/Python/bin/python: not found
farg967:~/software/OpenCOR-2024-08-23-Linux$ ./python -m pip install pandas
./python: 7: /home/farg967/software/OpenCOR-2024-08-23-Linux/Python/bin/python: not found

Let me know if i'm missing something?

**Comment by agarny** [comment]
Yes, sorry, I originally uploaded a version that has neither the `pip` script nor our copy of Python. My bad! I have fixed it and I am about to upload a new version. Will send an email to the mailing-list once I am done.

**Comment by agarny** [comment]
@FinbarArgus: heads-up, the new binaries for the 2024-08-23 snapshot have just been uploaded. I have tested the Linux one in my Docker and, from what I can tell, it all works fine. (I tried the `python` and `pip` scripts while I have tests for the `release_all_values()` method so it should still work.)

**Comment by FinbarArgus** [comment]
Works almost perfectly. Everything was super easy to install... apart from libcellml ?

`./pip install libcellml
ERROR: Could not find a version that satisfies the requirement libcellml (from versions: none)
ERROR: No matching distribution found for libcellml
farg967:~/software/OpenCOR-2024-08-23-Linux$ ./pip install libcellml==0.3.102
ERROR: Could not find a version that satisfies the requirement libcellml==0.3.102 (from versions: none)
ERROR: No matching distribution found for libcellml==0.3.102`

**Comment by agarny** [comment]
> Works almost perfectly. Everything was super easy to install... apart from libcellml ?
> 
> ```
> ./pip install libcellml
> ERROR: Could not find a version that satisfies the requirement libcellml (from versions: none)
> ERROR: No matching distribution found for libcellml
> farg967:~/software/OpenCOR-2024-08-23-Linux$ ./pip install libcellml==0.3.102
> ERROR: Could not find a version that satisfies the requirement libcellml==0.3.102 (from versions: none)
> ERROR: No matching distribution found for libcellml==0.3.102
> ```

If anything, this is an issue with libCellML Not sure whether we have a wheel for Ubuntu 22.04 LTS. Might want to [ask in our libCellML repo](https://github.com/cellml/libcellml/issues/new). @hsorby is the one dealing with libCellML packaging.
